version: '3.4'
services:
  part_6:
    container_name: part_6
    image: 'nginx:1.23.1-alpine'
    ports:
      - '80:8080'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
  part_4:
    container_name: part_4
    build: ../part_4/
    volumes:
      - '../part_4/nginx:/etc/nginx/conf.d'
